### ISSUE TITLE
Node js is mandatory? 

### ISSUE THREAD

**Issue by nicoprofe** [facemoji/mocap4face#10]
Hey! Can I run js-example/src/index.html in my server directly in javascript without node js?

**Comment by karelp** [comment]
Hey, it is possible to only use NPM to build the resulting JS package - use `npm run build` command for that. This command creates a standalone version in dist/ folder that you can then copy to your server. It is not possible to build the example without NPM because it is used to download dependencies (tensorflow.js) and do JS bundling and optimizations.
